import Head from 'next/head';
import { Roboto } from 'next/font/google';

// to run , type: pnpm dev
// left off at 37:30 in the tutorial: https://www.youtube.com/watch?v=I7XvhVHEam0


const roboto = Roboto( { subsets: ['latin'], weight: ['400'] } );

const links = [
  {
    title: 'LinkedIn',
    description: 'Work Experience',
    url: 'https://www.linkedin.com/in/maddalen-demars-35645692/'
  },
  {
    title: 'Professional Projects',
    description: 'Games and Mobile Applications',
    url: 'unknown'
  },
  {
    title: 'Personal Projects',
    description: 'Games and Mobile Applications',
    url: 'unknown'
  }
];

export default function Home() {
  return (
    <>
    <Head>
      <title>Create Next App</title>
      <meta name='description' content='Generated by create next app' />
      <meta name='viewport' content='width=device-width, initial-scale=1' />
    </Head>
    <main>
      <div>
        Maddalen DeMars
      </div>
      <div>
        <a href="#linkedin">LinkedIn</a>
        <a href="#professional">Professional Projects</a>
        <a href="#personal">Personal Projects</a>
      </div>
      <div>
        {links.map((link) => (
          <a key={link.url} href={link.url}>
            <span>{link.title}</span>
            <span>{link.description}</span>
          </a>
        ))}
      </div>
    </main>
    </>
  );
}
